name: Format

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format_if_merged:
    if: ${{ (github.event == 'pull_request' && github.event.pull_request.merged == true) || github.event == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Format with rustfmt
      run: cargo fmt
    - name: Fix with clippy
      run: cargo clippy --fix --allow-dirty --allow-staged
    - name: Push changes (if any)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -am "Automated formatting"
        git push
