name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   env:
    #     SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PASSWORD: ${{ secrets.PASSWORD }}
    #   run: cargo test --verbose
    - name: Install dependencies for generating node bindings
      run: cargo install nj-cli
    - name: Generate node bindings
      run: nj-cli build --release -- --features node
    - name: Generate typescript types
      run: cargo test --features node-types
